# Based on https://github.com/tengattack/certbot-dns-aliyun/blob/master/snap/snapcraft.yaml
name: certbot-dns-dnspod
version: '0.24.1'
summary: DNSPod DNS Authenticator plugin for Certbot
description: A certbot dns plugin to obtain certificates using dnspod.
confinement: strict

grade: stable
base: core20
adopt-info: certbot-dns-dnspod

parts:
  certbot-dns-dnspod:
    plugin: python
    source: .
    constraints: [$SNAPCRAFT_PART_SRC/snap-constraints.txt]
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version $SNAPCRAFT_PART_SRC/setup.py | cut -f2 -d= | tr -d "'[:space:]"`
    build-environment:
      - SNAP_BUILD: "True"
    # To build cryptography and cffi if needed
    build-packages: [gcc, libffi-dev, libssl-dev, python3-dev]
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        snapcraftctl pull
        mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared
slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
